### ISSUE TITLE
existsFile -> fileExists

### ISSUE THREAD

**Issue by dlesnoff** [pietroppeter/nimoji#14]
/tmp/nimble_35855/githubcom_pietroppeternimoji/src/nimoji.nim(59, 12) Warning: use fileExists; existsFile is deprecated [Deprecated]

Got this message at installation.

**Comment by pietroppeter** [comment]
should be a pretty simple PR if you want to do it: a one line change here https://github.com/pietroppeter/nimoji/blob/d8665bac0bab456e77dbae6abb8610145ffd33c2/src/nimoji.nim#L59

+ also bumping patch version so that after that I can tag a release

**Comment by pietroppeter** [comment]
fixed by #15
